name: Rust Setup
description: Install Rust toolchain and setup the runner cache

runs:
  using: "composite"
  steps:
    - name: Install stable toolchain
      id: toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Run sccache-cache only on non-release runs
      if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
      uses: mozilla-actions/sccache-action@v0.0.7

    - name: Set Rust caching env vars only on non-release runs
      if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
