[package]
name = "pasfmt-orchestrator"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
clap = { version = "4.3.8", features = ["derive"] }
encoding_rs = "0.8.32"
glob = "0.3.1"
pasfmt-core = { path = "../core" }
rayon = "1.7.0"
toml = "0.7.5"
walkdir = "2.3.3"
log = "0.4"

[dev-dependencies]
yare = "1.0.2"
