[package]
name = "pasfmt"
version = "0.2.0-dev"
edition = "2021"

[dependencies]
encoding_rs = "0.8.32"
pasfmt-core = { path = "../core" }
pasfmt-orchestrator = { path = "../orchestrator" }
serde = "1.0.164"
serde_derive = "1.0.164"
stderrlog = "0.5.4"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "benchmark_submodules"
harness = false

[lib]
bench = false