[package]
name = "pasfmt"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
pasfmt-core = { path = "../pasfmt-core" }
pasfmt-orchestrator = { path = "../pasfmt-orchestrator" }
serde = "1.0.164"
serde_derive = "1.0.164"
