[package]
name = "pasfmt-core"
version = "0.2.0-dev"
edition = "2021"

[dependencies]
itertools = "0.11.0"
nom = "7.1.3"
log = "0.4"

[dev-dependencies]
spectral = { version = "0.6.0", default-features = false }
indoc = "2.0.1"
yare = "1.0.2"
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.5"
paste = "1.0.14"

[[bench]]
name = "benchmark_lexer"
harness = false

[lib]
bench = false