name: Rust CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/workflows/setup/

      - run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/workflows/setup/

      - run: cargo test --all

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/workflows/setup/

      - run: cargo fmt --all -- --check
